# Generated by Django 4.2.7 on 2023-11-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
