# Generated by Django 4.2.7 on 2023-11-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employees_address_alter_employees_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
